### ISSUE TITLE
1.1.6 版本未上传bintray

### ISSUE THREAD

**Issue by linking123** [kongzue/StackLabel#5]
[bintray搜索结果](https://bintray.com/search?query=StackLabel)仍是1.1.5.1版本，Jul 16, 2019上传

**Comment by kongzue** [comment]
很抱歉出现此问题，已经重新上传

**Comment by linking123** [comment]
> 很抱歉出现此问题，已经重新上传

谢谢支持。关于另外一个未关闭issues 超出屏幕问题，可有解决的打算呢？

**Comment by kongzue** [comment]
当仅存在单个label且其长度超出屏幕的情况本来没有在我的考虑范围内，不过后续会对此问题进行修复，label一般情况下主要用于搜索结果、建议等场景，出现超出宽度范围的情况很少见，请持续关注更新日志，感谢您的反馈。

**Comment by linking123** [comment]
好的，万分感谢
