### ISSUE TITLE
如果一个标签内容过长，会超出屏幕宽度。

### ISSUE THREAD

**Issue by nxnyk** [kongzue/StackLabel#8]

**Comment by nxnyk** [comment]
![image](https://user-images.githubusercontent.com/42330422/66990554-04d37280-f0f9-11e9-8690-0ff1a8b73798.png)
如图

**Comment by kongzue** [comment]
是会出现这问题，因为设置了标签仅限单行。
此问题会在后续版本修复

**Comment by kongzue** [comment]
请更新 1.1.7 版本
